### ISSUE TITLE
✨ Route 생성 및 firebase 연결

### ISSUE THREAD

**Issue by kkang123** [kkang123/commerce#1]
# 📑 Description
Route 생성 후 public / private 구분
firebase 연결 후 회원가입 로그인 기능만 구현

# 📝 Todo
- [x] Route 생성 
- [x]  페이지 public / private 구분
- [x] React Context API로 로그인 상태관리
- [x] firebase 연결
- [x] 회원가입 로그인 기능 구현

# 📍 ETC
기타사항

**Comment by kkang123** [comment]
실수로 main에서 작업...
