### ISSUE TITLE
🎨 seller product Page Style

### ISSUE THREAD

**Issue by kkang123** [kkang123/commerce#15]
# 📑 Description
구매자가 상품 정보를 볼 수 있는 페이지 생성

# 📝 Todo
- [x] 홈 화면에 카테고리별 상품 표시 페이지 생성(4개씩 표시)
- [x] 카테고리 상품 페이지
- [x] 상품 상세 페이지(구매자가 상품을 구매할 수 있는 페이지)
- [x] 카테고리 페이지 기능 구현 및 스타일 (무한스크롤)

# 📍 ETC
기타사항
