### ISSUE TITLE
✨ Home, sellingproductPage feature

### ISSUE THREAD

**Issue by kkang123** [kkang123/commerce#19]
# 📑 Description

# 📝 Todo
- [x] 판매 상세 페이지에 동일 카테고리 물풀 추천 띄우기
- [x] 홈화면에 카테고리별 상품 정보 데이터로 표시
- [x] 이미지가 여러개라면 캐러셀로 이미지 표시

# 📍 ETC
기타사항
