### ISSUE TITLE
🔨 최종 Refactor

### ISSUE THREAD

**Issue by kkang123** [kkang123/commerce#54]
# 📑 Description
완성된 상태에서 미흡한 부분이나 부자연스러운 부분 수정, 추가적인 성능 개선 및 CSS 개선을 목표를 두기

# 📝 Todo
- [ ] 성능개선
- [ ] CSS 개선
- [ ] 미흡하거나 부자연스러운 부분 추가 예정
- [x] 게시물 삭제 시 firebase storage 이미지 삭제
- [x] 구글 소셜 로그인 추가

# 📍 ETC
기타사항

**Comment by kkang123** [comment]
결제 할 때 주소지 등록을 카카오 api를 호출해서 입력하는 기능 추가하기
